const=products=[
 {
  id:1,
  img:"../img/hero_img_1.svg",
  title:"Вариативный замок Golden Soft для отеля",
  price:"7 000₽",
  realPrice:"8 000₽",
  categories:["Popular","Price"],
  rating:"20",
  description:"nimadir",
  hasBasket:false,
 },
 {
  id:2,
  img:"../img/hero_img_2.svg",
  title:"Дверной Замок Golden Soft для офиса",
  price:"33 000₽",
  realPrice:"39 000₽",
  categories:["Popular","Price"],
  rating:"20",
  description:"nimadir",
  hasBasket:false,
 },
 {
  id:3,
  img:"../img/hero_img_3.svg",
  title:"Вариативный замок Golden Soft для отеля",
  price:"9 000₽",
  realPrice:"12 000₽",
  categories:["Popular","Price"],
  rating:"20",
  description:"nimadir",
  hasBasket:false,
 },
 {
  id:4,
 img:"../img/hero_img_1.svg",
 title:"Вариативный замок Golden Soft для отеля",
 price:"7 000₽",
 realPrice:"8 000₽",
 categories:["Popular","Price"],
 rating:"20",
 description:"nimadir",
 hasBasket:false,
},
{
 id:5,
 img:"../img/hero_img_2.svg",
 title:"Дверной Замок Golden Soft для офиса",
 price:"33 000₽",
 realPrice:"39 000₽",
 categories:["Popular","Price"],
 rating:"20",
 description:"nimadir",
 hasBasket:false,
},
{
 id:6,
 img:"../img/hero_img_3.svg",
 title:"Вариативный замок Golden Soft для отеля",
 price:"9 000₽",
 realPrice:"12 000₽",
 categories:["Popular","Price"],
 rating:"20",
 description:"nimadir",
 hasBasket:false,
},
{
 id:7,
img:"../img/hero_img_1.svg",
title:"Вариативный замок Golden Soft для отеля",
price:"7 000₽",
realPrice:"8 000₽",
categories:["Popular","Price"],
rating:"20",
description:"nimadir",
hasBasket:false,
},
{
id:8,
img:"../img/hero_img_2.svg",
title:"Дверной Замок Golden Soft для офиса",
price:"33 000₽",
realPrice:"39 000₽",
categories:["Popular","Price"],
rating:"20",
description:"nimadir",
hasBasket:false,
},
{
id:9,
img:"../img/hero_img_3.svg",
title:"Вариативный замок Golden Soft для отеля",
price:"9 000₽",
realPrice:"12 000₽",
categories:["Popular","Price"],
rating:"20",
description:"nimadir",
hasBasket:false,
},
{
 id:10,
img:"../img/hero_img_1.svg",
title:"Вариативный замок Golden Soft для отеля",
price:"7 000₽",
realPrice:"8 000₽",
categories:["Popular","Price"],
rating:"20",
description:"nimadir",
hasBasket:false,
},
{
id:11,
img:"../img/hero_img_2.svg",
title:"Дверной Замок Golden Soft для офиса",
price:"33 000₽",
realPrice:"39 000₽",
categories:["Popular","Price"],
rating:"20",
description:"nimadir",
hasBasket:false,
},
{
id:12,
img:"../img/hero_img_3.svg",
title:"Вариативный замок Golden Soft для отеля",
price:"9 000₽",
realPrice:"12 000₽",
categories:["Popular","Price"],
rating:"20",
description:"nimadir",
hasBasket:false,
},
]